/** @type {import('tailwindcss').Config} */
// tailwind.config.js
const colors = {
  primary: '#2563EB',
  nav: '#1E3A8A',
  accent: '#06B6D4',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  muted: '#6B7280',
  'bg-main': '#F9FAFB',
  'bg-card': '#FFFFFF',
  'bg-table-alt': '#F3F4F6',
  'text-primary': '#111827',
  'text-secondary': '#374151',
  'text-muted': '#6B7280',
  'text-link': '#2563EB',
  'role-admin': '#1E293B',
  'role-client': '#2563EB',
  'role-trainer': '#10B981',
  'role-moderator': '#8B5CF6',
  'role-superAdmin': '#8B5CF6',
  'role-superAdmins': '#8B5CF6',
  'role-alumni': '#8B5CF6',
  'role-coach': '#8B5CF6',
  'role-businessAdvisor': '#8B5CF6',
  'role-businessAdvisors': '#8B5CF6',
  'chart-blue': '#2563EB',
  'chart-emerald': '#10B981',
  'chart-cyan': '#06B6D4',
  'chart-rose': '#EF4444',
  'chart-amber': '#F59E0B',
  'table-header-bg': '#F9FAFB',
  'table-header-text': '#111827',
  'table-row-even': '#FFFFFF',
  'table-row-odd': '#F3F4F6',
  'table-hover': '#E0F2FE',
  'table-editable-border': '#06B6D4',
  'dashboard-card-bg': '#FFFFFF',
  'dashboard-text': '#111827',
  'dashboard-shadow': '#E5E7EB',
  'dashboard-uptrend': '#10B981',
  'dashboard-downtrend': '#EF4444',
  'form-label': '#374151',
  'form-border': '#D1D5DB',
  'form-focus': '#2563EB',
  'form-error': '#EF4444',
  'form-success': '#10B981',
  'form-placeholder': '#9CA3AF',
};

module.exports = {
  content: ['./src/**/*.{html,js,ts, tsx, jsx}'],
  theme: {
    extend: {
      colors: colors,
      animation: {
        'spin-slow': 'spin 8s linear infinite',
        'bounce-slow': 'bounce 3s infinite',
      },
    },
  },
  plugins: [],
};
